<template><div><h1 id="linux常用命令" tabindex="-1"><a class="header-anchor" href="#linux常用命令"><span>Linux常用命令</span></a></h1>
<h2 id="基础知识" tabindex="-1"><a class="header-anchor" href="#基础知识"><span>基础知识</span></a></h2>
<h3 id="linux-系统的文件结构" tabindex="-1"><a class="header-anchor" href="#linux-系统的文件结构"><span>Linux 系统的文件结构</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        二进制文件，系统常规命令</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">boot</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       系统启动分区，系统启动时读取的文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dev</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        设备文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">etc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        大多数配置文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">home</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       普通用户的家目录</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">lib</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        32位函数库</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">lib64</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      64位库</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">media</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      手动临时挂载点</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">mnt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        手动临时挂载点</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        第三方软件安装位置</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">proc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       进程信息及硬件信息</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">root</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       临时设备的默认挂载点</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sbin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       系统管理命令</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">srv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        数据</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">var</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        数据</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sys</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        内核相关信息</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tmp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        临时文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        用户相关设定</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="linux-命令行含义" tabindex="-1"><a class="header-anchor" href="#linux-命令行含义"><span>Linux 命令行含义</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">示例：root@app00:~#</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">root</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //用户名，root为超级用户</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">@       //分隔符</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">app00</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">   //主机名称</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">~       //当前所在目录，默认用户目录为~，会随着目录切换而变化，例如：（root@app00:/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"># ，当前位置在bin目录下）</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">#       //表示当前用户是超级用户，普通用户为$，例如：（</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"yao@app00:/root$"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ，表示使用用户</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"yao"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">访问/root文件夹）</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="命令组成" tabindex="-1"><a class="header-anchor" href="#命令组成"><span>命令组成</span></a></h3>
<p><code v-pre>命令 参数名 参数值</code></p>
<h2 id="基础操作" tabindex="-1"><a class="header-anchor" href="#基础操作"><span>基础操作</span></a></h2>
<h3 id="关闭系统" tabindex="-1"><a class="header-anchor" href="#关闭系统"><span>关闭系统</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">// 立刻关机</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">shutdown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">h</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> now</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 或者 poweroff</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">// 两分钟后关机</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">shutdown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">h</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">// 立刻重启</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">shutdown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> now</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 或者 reboot</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">// 两分钟后重启</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">shutdown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="帮助命令" tabindex="-1"><a class="header-anchor" href="#帮助命令"><span>帮助命令</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ifconfig</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  --</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">help</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //查看 ifconfig 命令的用法</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">man </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">shutdown</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //打开命令说明后，可按</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"q"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">键退出</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="切换用户" tabindex="-1"><a class="header-anchor" href="#切换用户"><span>切换用户</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">su </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">yao</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">               //切换为用户</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"yao"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,输入后回车需要输入该用户的密码</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">exit</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                 //退出当前用户</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="目录操作" tabindex="-1"><a class="header-anchor" href="#目录操作"><span>目录操作</span></a></h2>
<h3 id="切换目录" tabindex="-1"><a class="header-anchor" href="#切换目录"><span>切换目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">cd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /                 //切换到根目录</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">cd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              //切换到根目录下的bin目录</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">cd ../               //切换到上一级目录 或者使用命令：cd ..</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">cd ~                 //切换到home目录</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">cd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -                 //切换到上次访问的目录</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">cd </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">xx</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(文件夹名)       //切换到本目录下的名为xx的文件目录，如果目录不存在报错</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">cd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">xxx</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">xx</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">x</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //可以输入完整的路径，直接切换到目标目录，输入过程中可以使用tab键快速补全</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看目录" tabindex="-1"><a class="header-anchor" href="#查看目录"><span>查看目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                   //查看当前目录下的所有目录和文件</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">a</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                //查看当前目录下的所有目录和文件（包括隐藏的文件）</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                //列表查看当前目录下的所有目录和文件（列表查看，显示更多信息），与命令</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"ll"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">效果一样</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              //查看指定目录下的所有目录和文件</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建目录" tabindex="-1"><a class="header-anchor" href="#创建目录"><span>创建目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  mkdir </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tools</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">          //在当前目录下创建一个名为tools的目录</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  mkdir</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tools</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //在指定目录下创建一个名为tools的目录</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="删除目录和文件" tabindex="-1"><a class="header-anchor" href="#删除目录和文件"><span>删除目录和文件</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  rm 文件名              //删除当前目录下的文件</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 文件名           //删除当前目录的的文件（不询问）</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 文件夹名         //递归删除当前目录下此名的目录</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 文件夹名        //递归删除当前目录下此名的目录（不询问）</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> *              //将当前目录下的所有目录和文件全部删除</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /*             //将根目录下的所有文件全部删除【慎用！相当于格式化系统】</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改目录" tabindex="-1"><a class="header-anchor" href="#修改目录"><span>修改目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  mv 当前目录名 新目录名        //修改目录名，同样适用与文件操作</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  mv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tmp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tool</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //将/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/tmp目录下的tool目录剪切到 /opt目录下面</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  mv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tmp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tool</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //递归剪切目录中所有文件和文件夹</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="拷贝目录" tabindex="-1"><a class="header-anchor" href="#拷贝目录"><span>拷贝目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  cp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tmp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tool</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //将/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/tmp目录下的tool目录复制到 /opt目录下面</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  cp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tmp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tool</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //递归剪复制目录中所有文件和文件夹</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="搜索目录" tabindex="-1"><a class="header-anchor" href="#搜索目录"><span>搜索目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  find</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> 'a*'        //查找/bin目录下的所有以a开头的文件或者目录</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="查看当前目录" tabindex="-1"><a class="header-anchor" href="#查看当前目录"><span>查看当前目录</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  pwd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                         //显示当前位置路径</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="文件操作" tabindex="-1"><a class="header-anchor" href="#文件操作"><span>文件操作</span></a></h2>
<h3 id="新增" tabindex="-1"><a class="header-anchor" href="#新增"><span>新增</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">   touch  a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //在当前目录下创建名为a的txt文件（文件不存在），如果文件存在，将文件时间属性修改为当前系统时间</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="删除" tabindex="-1"><a class="header-anchor" href="#删除"><span>删除</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  rm 文件名              //删除当前目录下的文件</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 文件名           //删除当前目录的的文件（不询问）</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="编辑" tabindex="-1"><a class="header-anchor" href="#编辑"><span>编辑</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  vi 文件名              //打开需要编辑的文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  --进入后，操作界面有三种模式：命令模式（command mode）、插入模式（Insert mode）和底行模式（last line mode）</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  命令模式</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -刚进入文件就是命令模式，通过方向键控制光标位置，</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -使用命令</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"dd"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">删除当前整行</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -使用命令</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"/字段"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">进行查找</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -按</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"i"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">在光标所在字符前开始插入</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -按</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"a"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">在光标所在字符后开始插入</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -按</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"o"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">在光标所在行的下面另起一新行插入</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -按</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"："</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">进入底行模式</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  插入模式</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -此时可以对文件内容进行编辑，左下角会显示 </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"-- 插入 --""</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  -按"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">ESC</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"进入底行模式</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  </span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  底行模式</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  -退出编辑：      :q</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  -强制退出：      :q!</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  -保存并退出：    :wq</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  </span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  ## 操作步骤示例 ##</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  1.保存文件：按"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">ESC</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">" -> 输入"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">" -> 输入"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">wq</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">",回车     //保存并退出编辑</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  2.取消操作：按"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">ESC</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">" -> 输入"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">" -> 输入"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">q!</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">",回车     //撤销本次修改并退出编辑</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  ## 补充 ##</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  vim +10 filename.txt                   //打开文件并跳到第10行</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  vim -R /etc/passwd                     //以只读模式打开文件</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看" tabindex="-1"><a class="header-anchor" href="#查看"><span>查看</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  cat a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">          //查看文件最后一屏内容</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  less a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //PgUp向上翻页，PgDn向下翻页，</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"q"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">退出查看</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  more a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //显示百分比，回车查看下一行，空格查看下一页，</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"q"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">退出查看</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  tail</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -100</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //查看文件的后100行，</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Ctrl+C"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">退出查看</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="文件权限" tabindex="-1"><a class="header-anchor" href="#文件权限"><span>文件权限</span></a></h2>
<h3 id="权限说明" tabindex="-1"><a class="header-anchor" href="#权限说明"><span>权限说明</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  文件权限简介：</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">'r' 代表可读（4），'w' 代表可写（2），'x' 代表执行权限（1），括号内代表"8421法"</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ##文件权限信息示例：-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rwxrw</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">--</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -第一位：</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">'-'就代表是文件，'d'代表是文件夹</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -第一组三位：拥有者的权限</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -第二组三位：拥有者所在的组，组员的权限</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -第三组三位：代表的是其他用户的权限</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="文件授权" tabindex="-1"><a class="header-anchor" href="#文件授权"><span>文件授权</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  普通授权    </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">chmod</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> +</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">x</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.txt    </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  8421法     chmod </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">777</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">txt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">+</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">2</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">+</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">4</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">7</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">，</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"7"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">说明授予所有权限</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="打包与解压" tabindex="-1"><a class="header-anchor" href="#打包与解压"><span>打包与解压</span></a></h2>
<h3 id="说明" tabindex="-1"><a class="header-anchor" href="#说明"><span>说明</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .zip、.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //windows系统中压缩文件的扩展名</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              //Linux中打包文件的扩展名</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gz</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">               //Linux中压缩文件的扩展名</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .tar.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gz</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">           //Linux中打包并压缩文件的扩展名</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="打包" tabindex="-1"><a class="header-anchor" href="#打包"><span>打包</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zcvf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 打包压缩后的文件名 要打包的文件</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  参数说明：z：调用gzip压缩命令进行压缩; c：打包文件; v：显示运行过程; f：指定文件名;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  示例：</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zcvf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.tar file1 file2,...      //多个文件压缩打包</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="解压" tabindex="-1"><a class="header-anchor" href="#解压"><span>解压</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zxvf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                      //解包至当前目录</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zxvf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">tar</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">C</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">usr</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">------        //指定解压的位置</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  unzip test.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zip</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">             //解压*.zip文件 </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  unzip</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> test.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">zip</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">          //查看*.zip文件的内容</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="其他常用命令" tabindex="-1"><a class="header-anchor" href="#其他常用命令"><span>其他常用命令</span></a></h2>
<h3 id="find" tabindex="-1"><a class="header-anchor" href="#find"><span>find</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  find . -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "*.c"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //将目前目录及其子目录下所有延伸档名是 c 的文件列出来</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  find . -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //将目前目录其其下子目录中所有一般文件列出</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  find . -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ctime</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -20</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //将目前目录及其子目录下所有最近 </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">20</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 天内更新过的文件列出</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  find</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">var</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">log</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">mtime</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> +</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">7</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ok</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> rm {} \;     //查找/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">var</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/log目录中更改时间在7日以前的普通文件，并在删除之前询问它们</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  find . -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">perm</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 644</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">exec</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> {} \;       //查找前目录中文件属主具有读、写权限，并且文件所属组的用户和其他用户具有读权限的文件</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  find</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> / -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">size</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">exec</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> {} \;         //为了查找系统中所有文件长度为0的普通文件，并列出它们的完整路径</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  whereis </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ls</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">             //将和ls文件相关的文件都查找出来</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：which指令会在环境变量$PATH设置的目录里查找符合条件的文件。</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  which </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">bash</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">             //查看指令</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"bash"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">的绝对路径</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：sudo命令以系统管理者的身份执行指令，也就是说，经由 sudo 所执行的指令就好像是 root 亲自执行。需要输入自己账户密码。</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 使用权限：在 /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">etc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sudoers</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 中有出现的使用者</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  sudo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                              //列出目前的权限</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  $ </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sudo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">u</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> yao vi ~</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">www</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/index.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">html</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //以 yao 用户身份编辑  home 目录下www目录中的 index.html 文件</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  grep</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">i</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "the"</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> demo_file</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              //在文件中查找字符串(不区分大小写)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  grep</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">A</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">i</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "example"</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> demo_text</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //输出成功匹配的行，以及该行之后的三行</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  grep</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">r</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "ramesh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> *                   //在一个文件夹中递归查询包含指定字符串的文件</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：service命令用于运行System V init脚本，这些脚本一般位于/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">etc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/init.d文件下，这个命令可以直接运行这个文件夹里面的脚本，而不用加上路径</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service ssh </span><span style="--shiki-light:#986801;--shiki-dark:#ABB2BF">status</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //查看服务状态 </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  service</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> --</span><span style="--shiki-light:#986801;--shiki-dark:#ABB2BF">status</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">all</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //查看所有服务状态 </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service ssh </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">restart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //重启服务 </span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：这个命令用于显示系统当前内存的使用情况，包括已用内存、可用内存和交换内存的情况 </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  free</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">g</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            //以G为单位输出内存的使用量，-g为GB，-m为MB，-k为KB，-b为字节 </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  free</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">t</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            //查看所有内存的汇总</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  top</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">               //显示当前系统中占用资源最多的一些进程,</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> shift</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">+</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">m</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 按照内存大小查看</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：显示文件系统的磁盘使用情况</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  df</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">h</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            //一种易看的显示</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  mount</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dev</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sdb1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">u01</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              //挂载一个文件系统，需要先创建一个目录，然后将这个文件系统挂载到这个目录上</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  dev</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sdb1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">u01</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ext2 defaults </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">0</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">   //添加到fstab中进行自动挂载，这样任何时候系统重启的时候，文件系统都会被加载 </span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：uname可以显示一些重要的系统信息，例如内核名称、主机名、内核版本号、处理器类型之类的信息 </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  uname</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">a</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：安装插件命令</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  yum install </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">httpd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //使用yum安装apache </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  yum update </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">httpd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //更新apache </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  yum </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">remove</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> httpd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //卸载/删除apache </span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：插件安装命令</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rpm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ivh</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> httpd</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">-2.2.3-22.0.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.el5.i386.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rpm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //使用rpm文件安装apache </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rpm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">uvh</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> httpd</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">-2.2.3-22.0.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.el5.i386.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rpm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //使用rpm更新apache </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  rpm</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ev</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> httpd</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                                 //卸载/删除apache </span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">  date</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "01/31/2010 23:59:53"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">   ///设置系统时间</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 说明：使用wget从网上下载软件、音乐、视频 </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  // 示例：wget http://prdownloads.sourceforge.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">net</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sourceforge</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">nagios</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">nagios</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">-3.2.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.tar.gz</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  //下载文件并以指定的文件名保存文件</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  wget</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">O</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> nagios.tar.gz http://prdownloads.sourceforge.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">net</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sourceforge</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">nagios</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">nagios</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">-3.2.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.tar.gz</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ftp </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">IP</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">hostname</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //访问ftp服务器</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  mls *.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">html</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -       //显示远程主机上文件列表</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  scp</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> /</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/data.txt  </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">192.168.1.101</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">opt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/    //将本地opt目录下的data文件发送到192</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">.168.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.101服务器的opt目录下</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="系统管理" tabindex="-1"><a class="header-anchor" href="#系统管理"><span>系统管理</span></a></h2>
<h3 id="防火墙操作" tabindex="-1"><a class="header-anchor" href="#防火墙操作"><span>防火墙操作</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service iptables </span><span style="--shiki-light:#986801;--shiki-dark:#ABB2BF">status</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      //查看iptables服务的状态</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service iptables </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">start</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //开启iptables服务</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service iptables </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">stop</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //停止iptables服务</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  service iptables </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">restart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //重启iptables服务</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  chkconfig iptables </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">off</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //关闭iptables服务的开机自启动</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  chkconfig iptables </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">on</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //开启iptables服务的开机自启动</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ##centos7 防火墙操作</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  systemctl </span><span style="--shiki-light:#986801;--shiki-dark:#ABB2BF">status</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> firewalld.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">service</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //查看防火墙状态</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  systemctl stop firewalld.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">service</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //关闭运行的防火墙</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  systemctl disable firewalld.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">service</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //永久禁止防火墙服务</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改主机名-centos-7" tabindex="-1"><a class="header-anchor" href="#修改主机名-centos-7"><span>修改主机名（CentOS 7）</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  hostnamectl</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> set</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">hostname</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 主机名</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="查看网络" tabindex="-1"><a class="header-anchor" href="#查看网络"><span>查看网络</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ifconfig</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="修改ip" tabindex="-1"><a class="header-anchor" href="#修改ip"><span>修改IP</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  修改网络配置文件，文件地址：/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">etc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">sysconfig</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">network</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">scripts</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ifcfg</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">-</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">eth0</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ------------------------------------------------</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  主要修改以下配置：  </span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  TYPE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">Ethernet</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">               //网络类型</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  BOOTPROTO</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">static</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            //静态IP</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  DEVICE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ens00</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                //网卡名</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  IPADDR</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">192.168.1.100</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //设置的IP</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  NETMASK</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">255.255.255.0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //子网掩码</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  GATEWAY</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">192.168.1.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //网关</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  DNS1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">192.168.1.1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            //</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">DNS</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  DNS2</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">8.8.8.8</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                //备用DNS</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ONBOOT</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">yes</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                  //系统启动时启动此设置</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  -------------------------------------------------</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  修改保存以后使用命令重启网卡：service network restart</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看进程" tabindex="-1"><a class="header-anchor" href="#查看进程"><span>查看进程</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ps</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ef</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         //查看所有正在运行的进程</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="结束进程" tabindex="-1"><a class="header-anchor" href="#结束进程"><span>结束进程</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  kill </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">pid</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //杀死该pid的进程</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  kill</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -9</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> pid</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //强制杀死该进程</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看链接" tabindex="-1"><a class="header-anchor" href="#查看链接"><span>查看链接</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ping </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">IP</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //查看与此IP地址的连接情况</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  netstat</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">an</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    //查看当前系统端口</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  netstat</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> -</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">an</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | grep </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">8080</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     //查看指定端口</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="快速清屏" tabindex="-1"><a class="header-anchor" href="#快速清屏"><span>快速清屏</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">  ctrl</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">+</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        //清屏，往上翻可以查看历史操作</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="远程主机" tabindex="-1"><a class="header-anchor" href="#远程主机"><span>远程主机</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="shiki" data-ext="cmd" data-title="cmd" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  ssh </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">IP</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">       //远程主机，需要输入用户名和密码</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


